### ISSUE TITLE
Solr setup

### ISSUE THREAD

**Issue by caydenreynolds** [caydenreynolds/CS320_group_project#3]
Install and configure solr engine, and write a script to configure the engine

**Comment by HomeschoolMafia** [comment]
OK, so a summary of what I added:
Script to configure solr: configure_solr.py
Configuration for solr and default posting data are in the config directory

I wrote up install instructions for solr in the README, but since I modified setup.py, you guys will probably need to do a pip install of the project again for the changes to register.
